/* ============ 认名字模块 · 全班 37 位小朋友数据 ============ */
/* 每条: full 全名 | surname 姓 | given 名 | py 全名拼音 | surPy 姓拼音 */
window.CLASS_NAMES = [
  { full: "吴皓然", surname: "吴", given: "皓然", py: "wú hào rán",  surPy: "wú" },
  { full: "冉隆灏", surname: "冉", given: "隆灏", py: "rǎn lóng hào", surPy: "rǎn" },
  { full: "苗知时", surname: "苗", given: "知时", py: "miáo zhī shí", surPy: "miáo" },
  { full: "甘屹宸", surname: "甘", given: "屹宸", py: "gān yì chén",  surPy: "gān" },
  { full: "黄沐霖", surname: "黄", given: "沐霖", py: "huáng mù lín", surPy: "huáng" },
  { full: "王林奕", surname: "王", given: "林奕", py: "wáng lín yì",  surPy: "wáng" },
  { full: "梅谨辰", surname: "梅", given: "谨辰", py: "méi jǐn chén", surPy: "méi" },
  { full: "谌天心", surname: "谌", given: "天心", py: "chén tiān xīn", surPy: "chén" },
  { full: "王沫芊", surname: "王", given: "沫芊", py: "wáng mò qiān", surPy: "wáng" },
  { full: "王姝涵", surname: "王", given: "姝涵", py: "wáng shū hán", surPy: "wáng" },
  { full: "陈津彩", surname: "陈", given: "津彩", py: "chén jīn cǎi", surPy: "chén" },
  { full: "尹纶瑶", surname: "尹", given: "纶瑶", py: "yǐn lún yáo",  surPy: "yǐn" },
  { full: "孙书禾", surname: "孙", given: "书禾", py: "sūn shū hé",   surPy: "sūn" },
  { full: "熊昕禾", surname: "熊", given: "昕禾", py: "xióng xīn hé", surPy: "xióng" },
  { full: "叶瑾翊", surname: "叶", given: "瑾翊", py: "yè jǐn yì",     surPy: "yè" },
  { full: "欧阳君泽", surname: "欧阳", given: "君泽", py: "ōu yáng jūn zé", surPy: "ōu yáng" },
  { full: "卓杨梓夏", surname: "卓杨", given: "梓夏", py: "zhuó yáng zǐ xià", surPy: "zhuó yáng" },
  { full: "吴思霖", surname: "吴", given: "思霖", py: "wú sī lín",    surPy: "wú" },
  { full: "徐吴优", surname: "徐", given: "吴优", py: "xú wú yōu",    surPy: "xú" },
  { full: "徐一",   surname: "徐", given: "一",   py: "xú yī",        surPy: "xú" },
  { full: "廖锦瑞", surname: "廖", given: "锦瑞", py: "liào jǐn ruì", surPy: "liào" },
  { full: "邱谦",   surname: "邱", given: "谦",   py: "qiū qiān",     surPy: "qiū" },
  { full: "赵珩屹", surname: "赵", given: "珩屹", py: "zhào héng yì", surPy: "zhào" },
  { full: "张千越", surname: "张", given: "千越", py: "zhāng qiān yuè", surPy: "zhāng" },
  { full: "蒋乐其", surname: "蒋", given: "乐其", py: "jiǎng lè qí",  surPy: "jiǎng" },
  { full: "周梦涵", surname: "周", given: "梦涵", py: "zhōu mèng hán", surPy: "zhōu" },
  { full: "左沐灵", surname: "左", given: "沐灵", py: "zuǒ mù líng",  surPy: "zuǒ" },
  { full: "周煜婷", surname: "周", given: "煜婷", py: "zhōu yù tíng", surPy: "zhōu" },
  { full: "罗芮柠", surname: "罗", given: "芮柠", py: "luó ruì níng", surPy: "luó" },
  { full: "成乐怡", surname: "成", given: "乐怡", py: "chéng lè yí",  surPy: "chéng" },
  { full: "严子好", surname: "严", given: "子好", py: "yán zǐ hǎo",   surPy: "yán" },
  { full: "李星熠", surname: "李", given: "星熠", py: "lǐ xīng yì",   surPy: "lǐ" },
  { full: "黄晰一", surname: "黄", given: "晰一", py: "huáng xī yī",  surPy: "huáng" },
  { full: "曹星汉", surname: "曹", given: "星汉", py: "cáo xīng hàn", surPy: "cáo" },
  { full: "毕有哲", surname: "毕", given: "有哲", py: "bì yǒu zhé",   surPy: "bì" },
  { full: "薛善嘉", surname: "薛", given: "善嘉", py: "xuē shàn jiā", surPy: "xuē" },
  { full: "何希言", surname: "何", given: "希言", py: "hé xī yán",    surPy: "hé" }
];
